language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: "g+L1aPEoF6IIOteQk9DVcwzznU/h466Ymc3K7p9CMNlYNFdfpe9r3dviei1+R4juUD2ouVTrEteArrRxp7p4S0LRsJnwtgpPiAIf7DtIncfIGw/DsVSjG/1gTzqUyvUSlL24lY+4LCMhBUOuu+L0r4QP8vgZRw1y2aGirdRAiVU="
