language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: 0miZKNrN/k7LhSKR2FOJ5S6gnjTRNCTrQbj3Mp8amZxBuluHxRcxG+lyLT/X85xK8OOhBEcQxSkG+Tx5qQzYUliPBp7YFYs5rwX7x9FG4bTyPSRKwWCAU2b/yqViVb3m0kj3o39oFiUFycASsPeQUNvVGmJqyxf6iUC8yeUl3moQwjyhxq36Rn0f4/BkaktLAc8YojYtDOFVunZdFAOfVd/K04V/vFw/0os5PK8cFsK6wFdw+Hg/ViPWw/jiZUBrGXjkc+rJak4MYnPtArDuQwuUpSdFGEE1+BBhl0QQkXQTim1dj3bwL3/aSDW4crF0QOkfRAeRXgTSpmBembfauJWNwcc6+BOFqZXA2gEUGiW/AGtzJ+/LhiHjFpzIV2GP6bQMGVKbo9MjNjrguZ/i4w9uYQ/+Y588JeYF8IHF0wRfstGKCJOfkaiN6AoIYd96y2pJfVveunjFPvfhPF7uhw6WPJfh79BtECkdQpUxWlXBn7kGEEDTIWVkRkEA/0b4x0jL3vtfW4IPqBzfBz55yA0mTR8+whofw4iJieauIiHwqUULS/sans9QCWBUxQqogHEixeYwwZ2J4ABdg0fGRPCGG4UUlUkrBrdqO08D3XUdgWkxwQOLsq5z/REqs9YaDWolC0fAJmoNmqoAml4mRRORORzpQTTyWEbqBWiWVX8=
