language: node_js
node_js:
  - "0.12"
deploy:
  provider: heroku
  api_key:
    secure: "AAAAB3NzaC1yc2EAAAADAQABAAABAQDBpiLNe1pOvrh+BFFomDoqoiXoBcZVG1j0kCgHGUgaXvB80J3cFByqMZGQaPr5aHumLHH5XJZ0wa+3uvi7NGTafQSRqs3rRwXoccbTOYb9kbG+fD9NfS5AVqpQtSgcGnEb4LvRHDec8C1gKKTaxYp+l0LFeoCzqcCKmb/fgXNmWmQroQ96RBYDR40DQ7A9tJmQB0OB0p5yR6rZzFBu88vfjvdXqpzCll9FAi0S1jAXxznMmkluxFWGQ536lZRL5rsfvRYhm0jocOkvXQkNkiua2Ee6FcY8dxNeUSlb3usAYFu0X5ff9p4fSKW9lR1h9FPxYZ2EbUQReE8J/XnthP/7"