language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: npm
  email: slevins2008@mail.ru
  api_key:
    secure: 389d8308-c992-4a89-bd31-84cc9e94fae8
  on:
    tags: true
