language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    - secure: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCZ8WpesGuRQXwEYDnPl2yblU5+8thWHvHgorJ0GlZFaR0Nka9hU7w7T0A+/VaGXkJD+DmOJPDKqfE6b0fFB3vi6Tn4ivpF1qCMmtIki+UC04VgUOLMzY/UAtgMn4nN4bbCAxNtCtBcMtE0kI2Zs9vlHB3yHkb5sGPR1wzQiUPtgYirfxolyplMEQ/jHUKZsq+tPOJJ/BAtu2ycI1PxKDgLpj2vAUfBASalFJYcrlQw4xYSVugmsmyn+D3IlQN0ANqbn0gOWA7ji3H1M/Kyjqs6lybLNVRSMrM3gGT6nh3aXm2S8KaBwkEM6zFZI8evzYPM3+HGrcq6K1eoLUhylpaD"