language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: aGIgj5+6IGIelbThdp5M+SSdOZwidINs4ahsZn7+FZU3LyGH088CIlM7lOItYyVPdyYMeJj6AOGcZsVwwmb3mErQEkxMjLq2mKyiTPFKH9ebLpiJDTybQN+jUCGnshNHFc1D4NiRTpBcXJy6+VxhOXAB5r8l7N83GkFBkeyA9L8=
