language: node_js
node_js:
  - "0.12"
before_script:
  - npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: "AAAAB3NzaC1yc2EAAAADAQABAAABAQC1YyE9myS52QlB4DEj2thtFNYR0rqpGQM/sU2HppBRDgMW8bQFmggs2VAU4q4u14LDCbANgtOWWOJCfSqLHdn+kTMew1esAa71oycajjV+UFcQVitGKnFmL7AZrWwDMlCqHsMxxzFGuZu5R7FadVWy59frybHeWLmZBodDFDn/gIEeomCH4ntCxLlf9povMo9JvMH2zz4mhT+XI17ZQ7OAYuv4G8WuV3dgrCdHB8z6oIxDksg618SJtIa6UnEhgRPPEKbjOSA0o12RelocQ95VKXsQFRhG9WL4SX+ejgv8w1EL4x6OrNe572roPtV3YurCV3fiQNyYqAHwTflr+j3F"