language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: "rYfA83OPUPmIXSKfmNtV+v7sgP8KOfaeq4VDgQaYkFERHQxFoVjM7G8jqismpdHlEEjXVwrnmVoJ93yIJ9Dd4K1qTXlKl03jIiboDw0ZJWfIcKfLiZXwYsenw6go6JdrGsU28+pYZNg8p0SLjpHyyUZzeJXPPFVNb3wgO6v/Y8E8mWIQTq8OtMCWXmofm64vxCHkVeR2Z8Rg2yNS+IMLO+hGOvZdEI5EiPPgD56QxByhUCvCaY+E+fnrWeNjNT+1Eb9XHx5BUbPt8WYQSyQx9/470w/FfrXIZ9pNQQS6rQQhfnEYBayZkreSlN4GYPJacocfdElPG3nekqaWKi5C5Ja33+AMHwwUvMM2G1fS83e1rTiceUizS99NVHZKkgkdSQNS5H8QqUd9rr6vWXdQ3Ydbwfe4UI0ntxFsah6jX/LcNi6MCNy+8bMlTLnTIPlW5jVnalmgV2ftz/s3ZqbL9fxEohzHVDBaUDvJi/ZK1zKj3oW8BzeZ2bzYOLRfuQznwRT+HJwjJJZDXkgM/zMeL3FSpDhquGiambxu1KvqjtrCTgSIv0Fp2+X61x+k+6+EeAF41MZss8wGAbnFJSau2AwsRODJoUwYro3Yr31d5ueV+Y7K7kJyySmSXZezs1jKGY5OnTiq7HnzFbL8QjiBKHwkaoVZ2TEyFIkNIMc65/s="
