language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: npm
  email: "istomin.vlad1988@gmail.com"
  api_key:
    secure: "n2UqWcvphHHWiy152QZuaPB8YpYrOW+I5+lkfc2p+DAo7/CvM0ZW4EYahDJN2gO0mCZu9GRXIHs9wEqm6daEe5hC10lNJCXTx54Fqvoy3zYBaKpAxn2ayNFOEFHUlAC52XFaIetxRTw+/eu+7n9jj9rVsPPsPspPVo0/WqJ1HdunGtJ9PNleIsDPjcbBQsrb1JFlOdmEJ40VQZerqniTq4N6Ygg/YyVs1m7th/yv0pXyNWjEHB5oNs04gmt7kDwV8dmNR3e1I/VaeyNfJnU+GMWJ27WC2k6rzi6Lj2iN+4dql8Xm6jCnu/qVRv51Ln7bFv5NlLaz7S35qVlsI07ZIP1VRElQmpxaqwL65GH6TKWn1WQ44snDL99nRFoa0vJ+toJLyPWsCDU2rg2s6YcSFm4Dmu8Szup3ZGmWfNWxYyK9bIRzpl+jTlbWhy/qnt6ggQESJIi6LEzOJ4oqVnoWnHiE0/L44EJfFYRXSrT3FIunH6Oi8oNZbMueRqS9P8mdidq42dv6bvIta57uJge0GsVM/Lp/FSB/dR2I63e892MD1XSgdgL3ReYt51tXS9Cw74d7T2eiHvf9vLC6yk5mBwKwbEy1phLcJuSmJt549X/ffAwROYtkE5HLA/LUObGcJVMZe/9Op/VwJ6WiV4WURLLa+sRvu9nVkY9Bn1jqCMs="
  on:
    tags: true
