language: node_js
node_js:
- '0.12'
before_script:
- npm install -g gulp
script: gulp
deploy:
  provider: heroku
  api_key:
    secure: cTJbPHjArf8FU2TZ0aLWSCrd1+qHqhROjhHHf6yGHPJ9x+YXBGj0dFqcCkCMa7RsZ8JD8pw/hHweAuY2OPMVxVVB8nCYi2cQd4PQj2hkKDQtRt0u6T6hJarT/XX3Xn0jUoC7/rVJcjDq/jOK/oUZOh8qS5gtrsW30NRfwNU1Zx1JaXNikpw6gwpTHDFuMrlP1XVk+L7L04AJfoWJwKvCZAUQO98wpKksZ1H9Ut2Ykf4Ej/s+T0Zxq0VIDr9zPuIZZY5IgIBRA1M/Uo5Z+DwNCzQ3DTJHGGzd+N+6+uqMGDek1DXg9qp1aJ4pwSgH/iq2EGpnMTY83BxDDAncEFAr3rv20BQVz1jSOlAiQZyCtnAmOHBjTyu7MD9EYSTKFN+4Twk+TAXg8kF/pPeAUSK6jeClRAuDPNN3Jc1h4DKPbhmkCUpwnRWw9QHht8EWGuFjD6HXBGyusCnaXEujnvKAubDOtTlMdSI6u26q1ATHgR1HYON91czXw4DGygcb5iLSCQ9q4n+3vrk8F/mDNUmy5HLO06YJiBzuBKCx21q0oK1hYd7/0hpIgkF7P/AxEE9I20SOVL9tzSertCr9RE9FtXiouWQF404NqpAQ3Jmu5l1QWqRXz5m/Lx7ZqWrCbxIqw4FPBjBGtoSUi+Msll07qR1r7FimKmQrPHpEAJ0uVy8=
